"""add votes and sentiment columns to feedbacks table

Revision ID: 31557bcbfeca
Revises: ba01a0bced4f
Create Date: 2026-02-03 15:11:28.462067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31557bcbfeca'
down_revision: Union[str, Sequence[str], None] = 'ba01a0bced4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sentiment_enum = sa.Enum(
        'POSITIVE',
        'NEGATIVE',
        'NEUTRAL',
        name='sentimentenum'
    )

    sentiment_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('feedbacks', sa.Column(
        'sentiment', sentiment_enum, nullable=True)
    )
    op.add_column('feedbacks', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'votes')
    op.drop_column('feedbacks', 'sentiment')
    # ### end Alembic commands ###
